name: feather-press
services:
- name: web
  source_dir: /
  github:
    repo: ashitha1710/feather-press
    branch: main
  run_command: npm start
  build_command: npm ci && npm run build
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 3001
  health_check:
    http_path: /api/health
  envs:
  - key: NODE_ENV
    value: production
  - key: PORT
    value: "3001"
  - key: MYSQL_HOST
    value: ${MYSQL_HOST}
  - key: MYSQL_PORT
    value: ${MYSQL_PORT}
  - key: MYSQL_USER
    value: ${MYSQL_USER}
  - key: MYSQL_PASSWORD
    value: ${MYSQL_PASSWORD}
    type: SECRET
  - key: MYSQL_DATABASE
    value: ${MYSQL_DATABASE}
  - key: MYSQL_SSL
    value: "true"
  - key: STORAGE_PROVIDER
    value: spaces
  - key: SPACES_ENDPOINT
    value: ${SPACES_ENDPOINT}
  - key: SPACES_REGION
    value: ${SPACES_REGION}
  - key: SPACES_BUCKET
    value: ${SPACES_BUCKET}
  - key: SPACES_KEY
    value: ${SPACES_KEY}
    type: SECRET
  - key: SPACES_SECRET
    value: ${SPACES_SECRET}
    type: SECRET